import { Cake } from "./types";

export const cakes: Cake[] = [
  {
    id: 1,
    slug: "red-velvet",
    title: "Червоний оксамит",
    description: "Класичний торт із вершковим кремом.",
    category: "cakes",
    pricePerKg: 950,
    image: "/cakes/red-velvet.jpg",
    images: ["/cakes/red-velvet.jpg"],
    weights: [2, 3, 5],
    rating: 4.9,
    isPopular: true,
    available: true,
    shortDescription: "Насичений шоколадний торт.",

ingredients: [
  "Бельгійський шоколад",
  "Вершки 33%",
  "Вершкове масло",
  "Какао",
],

fillings: [
  "Шоколад",
  "Вишня",
  "Карамель",
],

storage: "Зберігати в холодильнику до 72 годин.",
  },
  {
    id: 2,
    slug: "napoleon",
    title: "Наполеон",
    description: "Домашній листковий торт.",
    category: "cakes",
    pricePerKg: 780,
    image: "/cakes/napoleon.jpg",
    images: ["/cakes/napoleon.jpg"],
    weights: [2, 3, 5],
    rating: 4.8,
    isPopular: true,
    available: true,
    shortDescription: "...",
ingredients: [],
fillings: [],
storage: "",
  },
  {
    id: 3,
    slug: "snickers",
    title: "Снікерс",
    description: "Шоколад, карамель і арахіс.",
    category: "birthday",
    pricePerKg: 920,
    image: "/cakes/snickers.jpg",
    images: ["/cakes/snickers.jpg"],
    weights: [2, 3, 5],
    rating: 5,
    isPopular: true,
    available: true,
    shortDescription: "...",
ingredients: [],
fillings: [],
storage: "",
  },
];